name: test-report-observability-action
description: Send test reports to Datadog

inputs:
  junit-xml-path:
    description: Glob pattern to the JUnit XML file(s)
    required: true
  metric-name-prefix:
    description: Prefix of the name of metrics
    required: true
    default: testreport
  filter-test-case-slower-than:
    description: Filter test cases slower than the threshold (in seconds)
    required: true
    default: '1'
  send-test-case-success:
    description: Send succeeded test cases
    required: true
    default: 'false'
  send-test-case-failure:
    description: Send failed test cases
    required: true
    default: 'true'
  codeowners:
    description: Path to the CODEOWNERS file
    required: false
  test-case-base-directory:
    description: Base directory to resolve the test case file path
    required: false
  enable-metrics:
    description: If false, do not send the metrics to Datadog
    required: true
    default: 'true'
  datadog-api-key:
    description: Datadog API key
    required: false
  datadog-site:
    description: Datadog site
    required: false
  datadog-tags:
    description: Datadog tags (key:value of multiline string)
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
